version: '3.8'

services:
  # Web Server for UI Testing
  web-server:
    build:
      context: .
      dockerfile: hostd/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - WEB_DASHBOARD_PORT=8080
    volumes:
      - ./hostd/src/web:/app/web
    command: ["cargo", "run", "--bin", "hostd"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Simple HTTP Server for Static Files (Alternative)
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./hostd/src/web:/usr/share/nginx/html
    profiles:
      - static

  # Redis for Session Storage (Optional)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    profiles:
      - full

  # PostgreSQL for Data Storage (Optional)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: guardian
      POSTGRES_USER: guardian
      POSTGRES_PASSWORD: guardian123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - full

volumes:
  postgres_data:
