version: '3.8'

services:
  # Main Minecraft server with Guardian Agent
  minecraft:
    build:
      context: .
      dockerfile: docker/Dockerfile.minecraft
    container_name: guardian-minecraft
    ports:
      - "25565:25565"
      - "25575:25575"  # RCON
    volumes:
      - ./data:/data
      - ./configs:/configs
      - ./mods:/mods
      - ./world:/world
    environment:
      - GUARDIAN_CONFIG=/configs/server.yaml
      - GUARDIAN_RULES=/configs/rules.yaml
    depends_on:
      - gpu-worker
      - hostd
    networks:
      - guardian-network
    restart: unless-stopped

  # GPU Worker for chunk generation acceleration
  gpu-worker:
    build:
      context: ./gpu-worker
      dockerfile: Dockerfile
    container_name: guardian-gpu-worker
    volumes:
      - /dev/dri:/dev/dri  # GPU access
      - ./data/gpu-cache:/cache
    environment:
      - RUST_LOG=info
      - GPU_WORKER_IPC=shm
    networks:
      - guardian-network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Watchdog daemon for process supervision
  hostd:
    build:
      context: ./hostd
      dockerfile: Dockerfile
    container_name: guardian-hostd
    ports:
      - "9090:9090"  # Prometheus metrics
    volumes:
      - ./data:/data
      - ./configs:/configs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RUST_LOG=info
      - HOSTD_CONFIG=/configs/hostd.yaml
    networks:
      - guardian-network
    restart: unless-stopped







networks:
  guardian-network:
    driver: bridge

