apiVersion: v1
kind: Namespace
metadata:
  name: guardian-server-manager
  labels:
    name: guardian-server-manager
    app.kubernetes.io/name: guardian-server-manager
    app.kubernetes.io/version: "1.0.0"
