# Guardian Host Daemon Configuration
minecraft:
  loader: "neoforge"
  version: "1.20.1"
  java:
    heap_gb: 4
    flags: "-Xmx4G -Xms2G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
    extra_flags: []

paths:
  mods_dir: "data/mods"
  config_dir: "data/configs"
  world_dir: "data/worlds"
  backup_dir: "data/backups"

compat:
  rules_file: "data/compat_rules.json"
  allow_bake_for_permissive_licenses: true
  auto_apply_rules: true
  rule_refresh_interval_minutes: 60

self_heal:
  entity_freeze_threshold: 1000
  block_entity_freeze_threshold: 500
  quarantine_dimension: "quarantine"
  thaw_on_rule_update: true
  max_frozen_entities: 10000
  max_frozen_block_entities: 5000

gpu:
  enabled: true
  worker_ipc: "tcp://127.0.0.1:8081"
  batch_size_chunks: 64
  max_cache_size: 1000
  health_check_interval_seconds: 30
  fallback_to_cpu: true

worldgen:
  gpu_acceleration: true
  async_generation: true
  pregeneration_enabled: true
  pregeneration_radius: 1000
  pregeneration_threads: 4

ha:
  autosave_minutes: 5
  snapshot_keep: 10
  blue_green: false
  rollback_on_failure: true
  max_restart_attempts: 3
  restart_delay_seconds: 30

monitoring:
  metrics_enabled: true
  metrics_port: 9090
  log_level: "info"
  crash_reporting: true

performance:
  tick_time_warning_ms: 50
  tick_time_critical_ms: 100
  memory_warning_percent: 80
  memory_critical_percent: 95
  gc_optimization: true

mod_configs:
  create:
    contraption_optimization: true
    flywheel_integration: true
    render_optimization: true
    batching_enabled: true
    shader_optimization: true
  flywheel:
    contraption_optimization: true
    flywheel_integration: true
    render_optimization: true
    batching_enabled: true
    shader_optimization: true
  embeddium:
    contraption_optimization: true
    flywheel_integration: true
    render_optimization: true
    batching_enabled: true
    shader_optimization: true